name       : ksanecore
version    : 23.04.3
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/ksanecore-23.04.3.tar.xz : f10c41e012f8f36ed5754951d1eaf0f325fcb6ad9ba3cf7ba568cd9a3c29ada5
homepage   : https://kde.org/
license    :
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Library providing logic to interface scanners
description: |
    KSaneCore is a library that provides a Qt interface for the SANE library for scanner hardware.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
