name       : ksanecore
version    : 22.12.1
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/ksanecore-22.12.1.tar.xz : add0e8d86161bee4271e3309c7e4f6323af1ded23127b10c6adcb5d560b0a433
homepage   : https://kde.org/
license    :
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Library providing logic to interface scanners
description: |
    KSaneCore is a library that provides a Qt interface for the SANE library for scanner hardware.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
