name       : ksanecore
version    : 23.04.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/ksanecore-23.04.0.tar.xz : 2434460fe67cf38293a1c90568ace1e52ffc8c3b6a1a57581d079d8237f482d8
homepage   : https://kde.org/
license    :
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Library providing logic to interface scanners
description: |
    KSaneCore is a library that provides a Qt interface for the SANE library for scanner hardware.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(sane-backends)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
